#!/usr/bin/python

""" 
Project Euler
Problem #2

http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the term of the even-valued terms.
"""

prevTerm = 0
currTerm = 1
nextTerm = 1
mySum = 0
while nextTerm <= 4000000:

    print "Sequence number: " + str(nextTerm)
    
    if  nextTerm % 2 == 0:
        mySum += nextTerm 
        print "Adding " + str(nextTerm) + " to the sum, which is now: " + str(mySum) + "."   
  
    tmp1 = prevTerm
    tmp2 = currTerm
    tmp3 = nextTerm

    nextTerm = tmp2 + tmp3
    currTerm = tmp3
    prevTerm = tmp2       
    
print "The sum of all even numbers in the fibonacci sequence not exceeding 4 million is " + str(mySum) 
